In [59]:
import torch

a = torch.zeros(2, 3, 5)
a.shape

torch.Size([2, 3, 5])

In [60]:
a

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [61]:
x = a.permute(2, 1, 0)

In [62]:
x.shape

torch.Size([5, 3, 2])

In [63]:
x

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [64]:
x = x.transpose(2, 1)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [65]:
x.shape

torch.Size([5, 2, 3])

In [66]:
x = torch.randn(4, 4)
x.numel()

16

In [67]:
x = x.view(2, 8)
x.shape

torch.Size([2, 8])

In [68]:
x = x.permute(1, 0)
x.numel()

16

In [69]:
x

tensor([[ 1.1806, -1.0037],
        [-0.1073, -0.2017],
        [ 1.2529, -1.4515],
        [ 1.0405,  0.5226],
        [-2.4221,  0.8468],
        [-0.7915,  1.6886],
        [ 1.0450,  1.4502],
        [-0.4707,  0.5785]])

In [70]:
x.view(4, 4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
x = x.reshape(4, 4)
x.shape

In [71]:
x = torch.rand(2, 1, 3)
x

tensor([[[0.2229, 0.0275, 0.5769]],

        [[0.1033, 0.5616, 0.4356]]])

In [72]:
y = x.squeeze(1)
y

tensor([[0.2229, 0.0275, 0.5769],
        [0.1033, 0.5616, 0.4356]])

In [76]:
z = y.squeeze(1)
z.shape

torch.Size([2, 3])

In [77]:
z = x.unsqueeze(1)
z

tensor([[[[0.2229, 0.0275, 0.5769]]],


        [[[0.1033, 0.5616, 0.4356]]]])