In [53]:
import torch

A = torch.ones(3, 3)
B = 2 * torch.ones(3, 3)
A

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [54]:
B

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [55]:
C = torch.cat((A, B), 0)
C

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [56]:
C = torch.cat((A, B), 1)
C

tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])

In [57]:
A = torch.arange(0, 4)
A

tensor([0, 1, 2, 3])

In [58]:
B = torch.arange(5, 9)
B

tensor([5, 6, 7, 8])

In [59]:
C = torch.stack((A, B), 0)
C

tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])

In [60]:
D = torch.stack((A, B), 1)
D

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]])

In [62]:
E = torch.stack((A.unsqueeze(0), B.unsqueeze(0)), 0)
E

tensor([[[0, 1, 2, 3]],

        [[5, 6, 7, 8]]])

In [63]:
A = torch.arange(1, 11)
B = torch.chunk(A, 2, 0)
B

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

In [66]:
B = torch.chunk(A, 3, 0)
B

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]), tensor([ 9, 10]))

In [67]:
A = torch.tensor([1, 2, 3])
B = torch.chunk(A, 5, 0)
B

(tensor([1]), tensor([2]), tensor([3]))

In [68]:
A = torch.ones(4, 4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [69]:
B = torch.chunk(A, 2, 0)
B

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [71]:
A = torch.rand(4, 4)
A

tensor([[0.0614, 0.1470, 0.2551, 0.1549],
        [0.4094, 0.5044, 0.3616, 0.9031],
        [0.2787, 0.0873, 0.9863, 0.2377],
        [0.3299, 0.7725, 0.2043, 0.5820]])

In [73]:
B = torch.split(A, 2, 1)
B

(tensor([[0.0614, 0.1470],
         [0.4094, 0.5044],
         [0.2787, 0.0873],
         [0.3299, 0.7725]]),
 tensor([[0.2551, 0.1549],
         [0.3616, 0.9031],
         [0.9863, 0.2377],
         [0.2043, 0.5820]]))

In [74]:
A = torch.arange(0, 16).view(4, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [75]:
B = torch.unbind(A, 0)
B

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]))

In [76]:
A = torch.arange(0, 16).view(4, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [77]:
B = torch.index_select(A, 0, torch.tensor([1, 3]))
B

tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])

In [78]:
C = torch.index_select(A, 1, torch.tensor([0, 3]))
C

tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])

In [83]:
A = torch.rand(5)
A

tensor([0.4426, 0.9303, 0.2830, 0.4927, 0.6385])

In [84]:
B = A > 0.3
B

tensor([ True,  True, False,  True,  True])

In [85]:
C = torch.masked_select(A, B)
C

tensor([0.4426, 0.9303, 0.4927, 0.6385])

In [86]:
A = torch.tensor([[4, 5, 7], [3, 9, 7], [2, 3, 4]])
A

tensor([[4, 5, 7],
        [3, 9, 7],
        [2, 3, 4]])

In [91]:
B = torch.tensor([[1, 0, 0], [0, 1, 1], [0, 0, 1]])
B

tensor([[1, 0, 0],
        [0, 1, 1],
        [0, 0, 1]])

In [93]:
C = torch.masked_select(A, B > 0)
C

tensor([4, 9, 7, 4])