In [1]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y.shape

torch.Size([3, 4])

In [2]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [3]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [4]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [5]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [6]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [8]:
import pandas as pd

# 创建一个简单的DataFrame
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
        'age': [25, 31, 35, 19],
        'score': [85.3, 63.2, 88.7, 75.8]}
df = pd.DataFrame(data)
df

name  age  score
0    Alice   25   85.3
1      Bob   31   63.2
2  Charlie   35   88.7
3    David   19   75.8

In [13]:
# 使用iloc选择第一行
print(df.iloc[0])
print("---------------------------------")
# 使用iloc选择前两行
print(df.iloc[0:2])
print("---------------------------------")
# 使用iloc选择第二列
print(df.iloc[:, 1])
print("---------------------------------")
# 使用iloc选择特定的单元格（第二行，第三列）
print(df.iloc[1:4, 0:2])

name     Alice
age         25
score     85.3
Name: 0, dtype: object
---------------------------------
    name  age  score
0  Alice   25   85.3
1    Bob   31   63.2
---------------------------------
0    25
1    31
2    35
3    19
Name: age, dtype: int64
---------------------------------
      name  age
1      Bob   31
2  Charlie   35
3    David   19
