In [5]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A, A.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]))

In [7]:
A.sum(), A.numel()

(tensor(190.), 20)

In [4]:
A_sum_0 = A.sum(axis=0)
A_sum_0

tensor([40., 45., 50., 55.])

In [6]:
A_sum_1 = A.sum(axis=1)
A_sum_1

tensor([ 6., 22., 38., 54., 70.])