In [1]:
import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, data_tensor, target_tensor):
        self.data_tensor = data_tensor
        self.target_tensor = target_tensor

    def __len__(self):
        return self.data_tensor.size(0)

    def __getitem__(self, index):
        return self.data_tensor[index], self.target_tensor[index]

In [20]:
data_tensor = torch.randn(10, 3)
target_tensor = torch.randint(2, (10,))
print(data_tensor)
print(target_tensor)

tensor([[-1.2996, -0.3030, -1.5320],
        [ 0.9622, -1.0867,  1.6007],
        [ 0.3840, -1.1482, -0.8537],
        [-0.3359, -0.6236, -0.6794],
        [ 0.8212,  0.9929,  0.9618],
        [-0.0872, -0.3316,  0.7315],
        [ 0.3311, -0.5363,  0.2185],
        [ 0.1324, -0.7167,  0.2304],
        [-1.2519,  0.8025, -0.7920],
        [-0.4599,  1.8695, -1.6432]])
torch.Size([10])


In [4]:
my_dataset = MyDataset(data_tensor, target_tensor)
print('Dataset size: ', len(my_dataset))

Dataset size:  10


In [5]:
print('tensor_data[0]: ', my_dataset[0])

tensor_data[0]:  (tensor([ 1.5626,  0.0603, -0.4698]), tensor(1))


In [6]:
from torch.utils.data import DataLoader

tensor_dataloader = DataLoader(dataset=my_dataset, batch_size=2, shuffle=True, num_workers=0)

In [7]:
for data, target in tensor_dataloader:
    print(data, target)

tensor([[ 1.5525,  1.1008,  1.3838],
        [ 0.1875, -1.4634, -0.1320]]) tensor([0, 0])
tensor([[-0.3038, -0.0422, -1.4879],
        [-0.2353, -0.8179,  0.0160]]) tensor([0, 1])
tensor([[-0.4191,  0.4035,  0.1726],
        [ 1.5626,  0.0603, -0.4698]]) tensor([0, 1])
tensor([[ 0.0215,  0.0765,  0.5617],
        [-0.4231,  1.6760, -1.4028]]) tensor([1, 1])
tensor([[ 0.5973,  2.0535,  1.1338],
        [ 1.6432, -0.7690, -0.6045]]) tensor([1, 0])


In [10]:
print('One batch tensor data: ', iter(tensor_dataloader).next())

One batch tensor data:  [tensor([[-0.4231,  1.6760, -1.4028],
        [ 1.5626,  0.0603, -0.4698]]), tensor([1, 1])]


In [11]:
import torchvision

minist_dataset = torchvision.datasets.MNIST(root='./data', train=True, transform=None, target_transform=None, download=True)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data\MNIST\raw



In [13]:
minist_dataset_list = list(minist_dataset)
display(minist_dataset_list[0][0])
print('Image label is: ', minist_dataset_list[0][1])

Image label is:  5
