### 2.2 数据操作
#### 2.2.1 创建`Tensor`

In [2]:
import torch

x = torch.empty(5, 3)
print(x)

tensor([[1.6486e+22, 4.3605e+27, 2.8929e+12],
        [7.5338e+28, 1.8037e+28, 3.4740e-12],
        [1.7743e+28, 2.0535e-19, 1.4609e-19],
        [7.5630e+28, 1.6745e+19, 7.5570e+28],
        [5.2839e-11, 1.7860e+31, 5.5342e-11]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7537, 0.1103, 0.1331],
        [0.4706, 0.7509, 0.3707],
        [0.1042, 0.8895, 0.6655],
        [0.3101, 0.4883, 0.5466],
        [0.1508, 0.6983, 0.0527]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3538, -0.1476, -1.5926],
        [-0.3983,  0.1769,  1.9292],
        [-0.3438,  1.4787, -1.0762],
        [-0.6693,  2.1470,  0.3175],
        [ 0.7095,  0.2383, -1.1342]])


In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### 2.2.2 操作

#### 算术操作

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1892,  0.3121, -0.9884],
        [-0.3767,  0.5573,  2.0192],
        [ 0.3249,  1.8370, -0.1795],
        [ 0.1272,  2.8142,  0.8430],
        [ 0.7288,  0.7223, -1.0945]])


In [9]:
print(torch.add(x, y))

tensor([[ 1.1892,  0.3121, -0.9884],
        [-0.3767,  0.5573,  2.0192],
        [ 0.3249,  1.8370, -0.1795],
        [ 0.1272,  2.8142,  0.8430],
        [ 0.7288,  0.7223, -1.0945]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1892,  0.3121, -0.9884],
        [-0.3767,  0.5573,  2.0192],
        [ 0.3249,  1.8370, -0.1795],
        [ 0.1272,  2.8142,  0.8430],
        [ 0.7288,  0.7223, -1.0945]])


In [11]:
y.add_(x)
print(y)

tensor([[ 1.1892,  0.3121, -0.9884],
        [-0.3767,  0.5573,  2.0192],
        [ 0.3249,  1.8370, -0.1795],
        [ 0.1272,  2.8142,  0.8430],
        [ 0.7288,  0.7223, -1.0945]])


#### 索引

In [12]:
y = x[0, :]
y += 1
print(y)
print(x[0, :])

tensor([ 1.3538,  0.8524, -0.5926])
tensor([ 1.3538,  0.8524, -0.5926])


#### 改变形状

In [13]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [14]:
x += 1
print(x)
print(y)

tensor([[ 2.3538,  1.8524,  0.4074],
        [ 0.6017,  1.1769,  2.9292],
        [ 0.6562,  2.4787, -0.0762],
        [ 0.3307,  3.1470,  1.3175],
        [ 1.7095,  1.2383, -0.1342]])
tensor([ 2.3538,  1.8524,  0.4074,  0.6017,  1.1769,  2.9292,  0.6562,  2.4787,
        -0.0762,  0.3307,  3.1470,  1.3175,  1.7095,  1.2383, -0.1342])


In [15]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.3538,  0.8524, -0.5926],
        [-0.3983,  0.1769,  1.9292],
        [-0.3438,  1.4787, -1.0762],
        [-0.6693,  2.1470,  0.3175],
        [ 0.7095,  0.2383, -1.1342]])
tensor([ 2.3538,  1.8524,  0.4074,  0.6017,  1.1769,  2.9292,  0.6562,  2.4787,
        -0.0762,  0.3307,  3.1470,  1.3175,  1.7095,  1.2383, -0.1342])


In [16]:
x = torch.randn(1)
print(x)
print(x.item)

tensor([0.7149])
<built-in method item of Tensor object at 0x0000026737B946D0>


In [17]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


2.2.4 运算的内存开销

In [18]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [19]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [20]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y)
print(id(y) == id_before)

True


### 2.2.5 `Tensor`和`Numpy`相互转换
#### `Tensor`转`Numpy`

In [21]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


#### `Numpy`数组转`Tensor`

In [22]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [23]:
# 返回的Tensor和原来的数据不再共享内存
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### 2.2.6 `Tensor` on GPU

In [24]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu"), torch.double)

tensor([2, 3], device='cuda:0')
tensor([2, 3]) torch.float64
