### 2.2 数据操作
#### 2.2.1 创建`Tensor`

In [10]:
import torch

x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7044, 0.9868, 0.5662],
        [0.6113, 0.1720, 0.9041],
        [0.8976, 0.9799, 0.6781],
        [0.8551, 0.4052, 0.1338],
        [0.8127, 0.7781, 0.2221]])


In [12]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [13]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [14]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4364, -2.0648, -1.2812],
        [ 0.3177, -0.1491,  0.3846],
        [-0.0901,  1.6214,  0.8612],
        [ 0.0432,  0.2209,  1.3998],
        [-0.8680, -0.8593,  1.4544]])


In [15]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### 2.2.2 操作

#### 算术操作

In [17]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.2635, -1.5984, -0.5047],
        [ 0.8327,  0.1675,  1.0149],
        [ 0.5319,  1.8554,  1.2741],
        [ 0.3852,  0.9254,  2.0302],
        [-0.7212, -0.2974,  2.1448]])


In [18]:
print(torch.add(x, y))

tensor([[ 2.2635, -1.5984, -0.5047],
        [ 0.8327,  0.1675,  1.0149],
        [ 0.5319,  1.8554,  1.2741],
        [ 0.3852,  0.9254,  2.0302],
        [-0.7212, -0.2974,  2.1448]])


In [20]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0745e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])
tensor([[ 2.2635, -1.5984, -0.5047],
        [ 0.8327,  0.1675,  1.0149],
        [ 0.5319,  1.8554,  1.2741],
        [ 0.3852,  0.9254,  2.0302],
        [-0.7212, -0.2974,  2.1448]])
